version: '3.9'
services:
  app:
    build: ./app
    ports:
      - '127.0.0.1:8000:8000'
    depends_on:
      - 'redis'

  redis:
    image: 'redis:6.2.4'
    volumes:
      - 'redis-data:/data'

volumes:
  redis-data:
